proxy: http://127.0.0.1:10811
cookie: 26338360_7co6cX1DcbRnqclbVWptSyzSSNrSanal
agelimit: true
downloadposition: D:\personal things\Download
likelimit: 3500
retry429: 10000
downloadinterval: 500
retryinterval: 2000
