// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckLogin() {
    return $Call.ByID(2311033350);
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function DownloadByAuthorId(text) {
    return $Call.ByID(898696052, text);
}

/**
 * @param {string} page
 * @param {string} Type
 * @returns {$CancellablePromise<boolean>}
 */
export function DownloadByFollowPage(page, Type) {
    return $Call.ByID(3071205656, page, Type);
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function DownloadByNovelId(text) {
    return $Call.ByID(2543971205, text);
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function DownloadByPid(text) {
    return $Call.ByID(2568205727, text);
}

/**
 * @param {string} text
 * @param {string} Type
 * @returns {$CancellablePromise<boolean>}
 */
export function DownloadByRank(text, Type) {
    return $Call.ByID(1546644368, text, Type);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function RegisterService(app) {
    return $Call.ByID(4158062649, app);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReturnString() {
    return $Call.ByID(3037929488);
}
