// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Ctl from "./ctl.js";
import * as GreetService from "./greetservice.js";
export {
    Ctl,
    GreetService
};
