// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLogin() {
  return window['go']['main']['App']['CheckLogin']();
}

export function DownloadByAuthorId(arg1) {
  return window['go']['main']['App']['DownloadByAuthorId'](arg1);
}

export function DownloadByFollowPage(arg1, arg2) {
  return window['go']['main']['App']['DownloadByFollowPage'](arg1, arg2);
}

export function DownloadByPid(arg1) {
  return window['go']['main']['App']['DownloadByPid'](arg1);
}

export function DownloadByRank(arg1, arg2) {
  return window['go']['main']['App']['DownloadByRank'](arg1, arg2);
}

export function PopFollowPool() {
  return window['go']['main']['App']['PopFollowPool']();
}

export function PopLoadPool() {
  return window['go']['main']['App']['PopLoadPool']();
}

export function PreloadFollow(arg1, arg2) {
  return window['go']['main']['App']['PreloadFollow'](arg1, arg2);
}

export function PreloadRank(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreloadRank'](arg1, arg2, arg3);
}

export function ReturnString() {
  return window['go']['main']['App']['ReturnString']();
}
