// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {DAO} from '../models';

export function CheckLogin():Promise<boolean>;

export function DownloadByAuthorId(arg1:string):Promise<boolean>;

export function DownloadByFollowPage(arg1:string,arg2:string):Promise<boolean>;

export function DownloadByPid(arg1:string):Promise<boolean>;

export function DownloadByRank(arg1:string,arg2:string):Promise<boolean>;

export function GetSetting():Promise<DAO.Settings>;

export function PopFollowPool():Promise<void>;

export function PopLoadPool():Promise<void>;

export function PreloadFollow(arg1:string,arg2:string):Promise<boolean>;

export function PreloadRank(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function ReturnString():Promise<string>;

export function UpdateSetting(arg1:DAO.Settings):Promise<void>;
