// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadByAuthorId(arg1:string):Promise<boolean>;

export function DownloadByPid(arg1:string):Promise<boolean>;

export function DownloadByRank(arg1:string,arg2:string):Promise<boolean>;

export function ReturnString():Promise<string>;
