// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadByAuthorId(arg1) {
  return window['go']['main']['App']['DownloadByAuthorId'](arg1);
}

export function DownloadByPid(arg1) {
  return window['go']['main']['App']['DownloadByPid'](arg1);
}

export function DownloadByRank(arg1, arg2) {
  return window['go']['main']['App']['DownloadByRank'](arg1, arg2);
}

export function PopLoadPool() {
  return window['go']['main']['App']['PopLoadPool']();
}

export function PreloadRank(arg1, arg2) {
  return window['go']['main']['App']['PreloadRank'](arg1, arg2);
}

export function ReturnString() {
  return window['go']['main']['App']['ReturnString']();
}
