// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MsgDetail() {
  return window['go']['DAO']['Settings']['MsgDetail']();
}

export function UpdateSettings(arg1) {
  return window['go']['DAO']['Settings']['UpdateSettings'](arg1);
}
