// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {DAO} from '../models';

export function MsgDetail():Promise<string>;

export function UpdateSettings(arg1:DAO.Settings):Promise<void>;
